apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mycluster1
  region: us-east-1

managedNodeGroups:
  - name: k8cluster
    instanceType: t3.medium
    minSize: 3
    maxSize: 5
    desiredCapacity: 5

availabilityZones: ["us-east-1a","us-east-1b","us-east-1c","us-east-1d"]